### ISSUE TITLE
github action for gh pages

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Palio-UNICT#1]
reference:
- https://github.com/UNICT-DMI/OPIS-Manager/blob/master/.github/workflows/main.yml
- https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by Helias** [comment]
it does not seem working, keep it open until it does not work

**Comment by scraccio** [comment]
Yes I actually pushed an old commit which mentioned this issue. I'm still trying to solve this

**Comment by scraccio** [comment]
Closing this issue, the action is now working
